# docker-compose.yml
services:
  blog:
    container_name: kcnet-blog
    # 从当前目录的 Dockerfile 构建镜像
    build: .
    ports:
      # 将你电脑的 8080 端口映射到容器的 80 端口
      # 这样你可以在浏览器中访问 http://localhost:8080
      - "8080:80"
    volumes:
      # 这个卷挂载可以实现热更新：你在本地 dist 文件夹做的任何修改，都会立刻反映到容器里，无需重启
      - ./dist:/usr/share/nginx/html:ro # ro = read-only, 更安全
    restart: unless-stopped